language: python
python:
  -"3.5"
virtualenv:
  system_site_packages: true
install:
  - pip install -e .
  - pip install codecov pytest-cov # Install packages for code coverage report
script:
  - pytest --cov=src tests # Point to the source directory
after_success:
  - codecov # Uploads report to codecov.io
